version: '3.6'
services:


    
  nginx:
    image:  calypsolon/nginx:1.0.0
    container_name: nginx
    ports:
     - "80:80"
    environment:
     - "API_SERVER=10.3.106.64"
    
  config-server:
    image: artifacts.calypso.com:18180/calypso/calypso-config-server:1.0.0-SNAPSHOT
    container_name: config-server
    ports:
    - "7000:8080"
    container_name: config-server

    environment:
    - "CATALINA_OPTS=-Xmx200m -Dport=7000 -DrepoURL=file:///tmp/git-config-repo"
    volumes:
        - /home/silvio/DockerDevTools/property_files/local_property_files:/tmp/git-config-repo

  kafka:
    image: calypsolon/kafka
    container_name: kafka
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
    - ADVERTISED_HOST=10.3.106.64
    - ADVERTISED_PORT=9092

  postgres:
    image: postgres
    container_name: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgress
    - POSTGRES_DB=postgres
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=silvio_piccolo@calypso.com
    - PGADMIN_DEFAULT_PASSWORD=SuperSecret  
    links:
    - postgres
    ports:
    - "5050:80"

volumes: 
  pgdata:
